name: Fork仓库更新A
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0/1 * * *
  
jobs: 
  build:
    runs-on: Ubuntu-20.04
    name: 拉取passerby-b/JDDJr仓库
    steps:
    - name: 拉取仓库到stanlyshi/JDDJ
      uses: roacn/github-forks-sync-action@master
      with:
        github_token: ${{ secrets.RELEASES_TOKEN }}
        upstream_repository: passerby-b/JDDJ
        upstream_branch: main
        target_repository: stanlyshi/JDDJ
        target_branch: main
        force: true
        tags: true
      
  build2:
    runs-on: Ubuntu-20.04
    name: 拉取JDHelloWorld/jd_scripts仓库
    steps:
    - name: 拉取仓库到stanlyshi/scripts_J
      uses: roacn/github-forks-sync-action@master
      with:
        github_token: ${{ secrets.RELEASES_TOKEN }}
        upstream_repository: JDHelloWorld/jd_scripts
        upstream_branch: main
        target_repository: stanlyshi/scripts_J
        target_branch: main
        force: true
        tags: true
        
  build3:
    runs-on: Ubuntu-20.04
    name: 拉取curtinlv/JD-Script仓库
    steps:
    - name: 拉取仓库到stanlyshi/scripts_JD
      uses: roacn/github-forks-sync-action@master
      with:
        github_token: ${{ secrets.RELEASES_TOKEN }}
        upstream_repository: curtinlv/JD-Script
        upstream_branch: main
        target_repository: stanlyshi/scripts_JD
        target_branch: main
        force: true
        tags: true

  build4:
    runs-on: Ubuntu-20.04
    name: 拉取yqchilde/JDMemberCloseAccount仓库
    steps:
    - name: 拉取仓库到stanlyshi/JDMemberCloseAccount
      uses: roacn/github-forks-sync-action@master
      with:
        github_token: ${{ secrets.RELEASES_TOKEN }}
        upstream_repository: yqchilde/JDMemberCloseAccount
        upstream_branch: main
        target_repository: stanlyshi/JDMemberCloseAccount
        target_branch: main
        force: true
        tags: true

  build5:
    runs-on: Ubuntu-20.04
    name: 拉取shufflewzc/Ariszy仓库
    steps:
    - name: 拉取仓库到stanlyshi/Ariszy
      uses: roacn/github-forks-sync-action@master
      with:
        github_token: ${{ secrets.RELEASES_TOKEN }}
        upstream_repository: shufflewzc/Ariszy
        upstream_branch: main
        target_repository: stanlyshi/Ariszy
        target_branch: main
        force: true
        tags: true
        
  build6:
    runs-on: Ubuntu-20.04
    name: 拉取panghu999/panghu仓库
    steps:
    - name: 拉取仓库到stanlyshi/panghu
      uses: roacn/github-forks-sync-action@master
      with:
        github_token: ${{ secrets.RELEASES_TOKEN }}
        upstream_repository: panghu999/panghu
        upstream_branch: master
        target_repository: stanlyshi/panghu
        target_branch: master
        force: true
        tags: true

  build7:
    runs-on: Ubuntu-20.04
    name: 拉取he1pu/JDHelp仓库
    steps:
    - name: 拉取仓库到stanlyshi/JDHelp
      uses: roacn/github-forks-sync-action@master
      with:
        github_token: ${{ secrets.RELEASES_TOKEN }}
        upstream_repository: he1pu/JDHelp
        upstream_branch: main
        target_repository: stanlyshi/JDHelp
        target_branch: main
        force: true
        tags: true

  build8:
    runs-on: Ubuntu-20.04
    name: 拉取shufflewzc/faker2仓库
    steps:
    - name: 拉取仓库到stanlyshi/faker2
      uses: roacn/github-forks-sync-action@master
      with:
        github_token: ${{ secrets.RELEASES_TOKEN }}
        upstream_repository: shufflewzc/faker2
        upstream_branch: main
        target_repository: stanlyshi/faker2
        target_branch: main
        force: true
        tags: true
        
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
